CREATE TABLE IF NOT EXISTS cfbd.drives (
    id serial,
    year smallint,
    offense varchar,
    offense_conference varchar,
    defense varchar,
    defense_conference varchar,
    game_id bigint,
    drive_id bigint,
    drive_number smallint,
    scoring boolean,
    start_period smallint,
    start_yardline smallint,
    start_ytg smallint,
    start_time_min smallint,
    start_time_sec smallint,
    end_period smallint,
    end_yardline smallint,
    end_ytg smallint,
    end_time_min smallint,
    end_time_sec smallint,
    plays smallint,
    yards smallint,
    drive_result character varying COLLATE pg_catalog."default",
    is_home_offense boolean,
    start_o_score smallint,
    start_d_score smallint,
    end_o_score smallint,
    end_d_score smallint,
    CONSTRAINT drives_pkey PRIMARY KEY (id)
);