CREATE TABLE IF NOT EXISTS cfbd.teams (
    id int,
    school varchar,
    mascot varchar,
    abbreviation varchar,
    alt_name1 varchar,
    alt_name2 varchar,
    alt_name3 varchar,
    conference varchar,
    classification varchar,
    color varchar,
    alt_color varchar,
    logo_1 varchar,
    logo_2 varchar,
    twitter varchar,
    location_venue_id int,
    location_name varchar,
    location_city varchar,
    location_state varchar,
    location_zip varchar,
    location_country_code varchar,
    location_timezone varchar,
    location_latitude float8,
    location_longitude float8,
    location_elevation float8,
    location_capacity int,
    location_year_constructed smallint,
    location_grass boolean,
    location_dome boolean,
    CONSTRAINT teams_pkey PRIMARY KEY (id)
);