CREATE TABLE IF NOT EXISTS cfbd.plays (
    id bigint,
    offense varchar,
    offense_conference varchar,
    defense varchar,
    defense_conference varchar,
    home varchar,
    away varchar,
    offense_score smallint,
    defense_score smallint,
    game_id bigint,
    drive_id bigint,
    drive_number smallint,
    play_number smallint,
    period smallint,
    clock_minutes smallint,
    clock_seconds smallint,
    offense_timeouts smallint,
    defense_timeouts smallint,
    yard_line smallint,
    yards_to_goal smallint,
    down smallint,
    distance smallint,
    scoring boolean,
    yards_gained smallint,
    play_type varchar,
    play_text varchar,
    ppa float8,
    wall_clock timestamp,
    CONSTRAINT plays_pkey PRIMARY KEY (id)
);